%{
#include "hpp.hpp"
%}
%defines %union { Sym*o; }
%token <o> SYM
%token <o> LC RC
%token <o> EQ AT COLON
%token <o> ADD
%type <o> ex lambda
%%
REPL : | REPL ex 		{ cout << $2->dump(); } ;
ex : SYM
	| LC lambda RC		{ $$=$2; }
	| EQ
	| ex AT ex			{ $$=new Sym($3->val+"pp"); }
;
lambda :				{ $$=new Lambda(); }
	| lambda SYM COLON	{ $$=$1; $$->par($2); }
	| lambda ex			{ $$=$1; $$->push($2); }
;
%%